### ISSUE TITLE
Details component - too much margin bottom on elements inside

### ISSUE THREAD

**Issue by cevangelougovcy** [gov-cy/govcy-design-system#152]
## What happened?
There is too much margin-bottom inside the elements in a detail

![image](https://github.com/user-attachments/assets/28b4d84a-be61-48bf-90a2-c425dfe585ae)

## Expected outcome?
The following style should fix it

```css
.govcy-details__text > :last-child {
    margin-bottom: 0px;
}
```

We can add it later to the UDS as a fix

![image](https://github.com/user-attachments/assets/7799cae6-db60-406e-b1dc-5838fadf5725)
