### ISSUE TITLE
Labels and legends inside conditional radios are too big

### ISSUE THREAD

**Issue by cevangelougovcy** [gov-cy/govcy-design-system#153]
## Cause
Labels and legends inside conditional radios are too big. Bigger than the option's label

![image](https://github.com/user-attachments/assets/2b37d0c1-657e-4a35-8c8b-07021690e12d)

## Change request

Make them same size as option's labels, Use the style below 

```css
.govcy-radio__conditional label,
.govcy-radio__conditional legend {
    font-size: 1rem !important;
}       
```

![image](https://github.com/user-attachments/assets/c2fb7c64-a56d-4b20-8042-bd23168d5880)
