### ISSUE TITLE
Fix `govcy-link-no-visited-state:focus` color

### ISSUE THREAD

**Issue by cevangelougovcy** [gov-cy/govcy-design-system#154]
The `.govcy-link-no-visited-state:focus` is wrong 
![image](https://github.com/user-attachments/assets/1b73b43d-00fe-45a6-b193-2c656fde3c2e)

Add this style:

```css
.govcy-link-no-visited-state:focus {
            color: #272525 !important;
        }
```

**Comment by cevangelougovcy** [comment]
Looks ok as is no change needed

**Comment by cevangelougovcy** [comment]
After further investigation its the `.govcy-link-no-visited-state:visited:focus ` which is wrong. It should be 

```css
.govcy-link-no-visited-state:visited:focus {
  color: #272525 !important;
}
```
